/**
 * Created by Yaroslav on 13.02.2018.
 */

export const GET_FASTPLACES_REQUEST = 'GET_FASTPLACES_REQUEST';
export const FAST_PLACES_RESULT = 'FAST_PLACES_RESULT';

export const GET_PLACE_BY_ID = 'GET_PLACE_BY_ID';
export const GET_PLACE_BY_ID_SUCCESS = 'GET_PLACE_BY_ID_SUCCESS';

export const GET_PLACES_BY_FILTER = 'GET_PLACES_BY_FILTER';
export const GET_PLACES_BY_FILTER_SUCCESS = 'GET_PLACES_BY_FILTER_SUCCESS';

export const FAST_PLACES_ON_MAP = 'FAST_PLACES_ON_MAP';

export const SEARCH_FILTER_EDIT = 'SEARCH_FILTER_EDIT';

export const SEARCH_PLACES_REQUEST = 'SEARCH_PLACES_REQUEST';
export const SEARCH_PLACES_SUCCES = 'SEARCH_PLACES_SUCCESS';

export const GET_DIRECTION_REQUEST = 'GET_DIRECTIONS_REQUEST';
export const GET_DIRECTION_ERROR = 'GET_DIRECTIONS_ERROR';
export const GET_DIRECTION_SUCCESS = 'GET_DIRECTIONS_SUCCESS';

export const HIDE_LOADER = 'HIDE_LOADER';
export const SET_ROUTE_DATA = 'SET_ROUTE_DATA';

export const CLOSE_ROUTE = 'CLOSE_ROUTE';