/**
 * Created by Yaroslav on 13.02.2018.
 */

export const GET_FASTPLACES_REQUEST = 'GET_FASTPLACES_REQUEST';
export const FAST_PLACES_RESULT = 'FAST_PLACES_RESULT';

export const GET_PLACE_BY_ID = 'GET_PLACE_BY_ID';
export const GET_PLACE_BY_ID_SUCCESS = 'GET_PLACE_BY_ID_SUCCESS';
