/**
 * Created by Yaroslav on 13.02.2018.
 */

export const GET_FASTPLACES_REQUEST = 'GET_FASTPLACES_REQUEST';
export const FAST_PLACES_RESULT = 'FAST_PLACES_RESULT';

export const GET_PLACE_BY_ID = 'GET_PLACE_BY_ID';
export const GET_PLACE_BY_ID_SUCCESS = 'GET_PLACE_BY_ID_SUCCESS';

export const GET_PLACES_BY_FILTER = 'GET_PLACES_BY_FILTER';
export const GET_PLACES_BY_FILTER_SUCCESS = 'GET_PLACES_BY_FILTER_SUCCESS';

export const FAST_PLACES_ON_MAP = 'FAST_PLACES_ON_MAP';

export const SEARCH_FILTER_EDIT = 'SEARCH_FILTER_EDIT';

export const SEARCH_PLACES_REQUEST = 'SEARCH_PLACES_REQUEST';
export const SEARCH_PLACES_SUCCES = 'SEARCH_PLACES_SUCCESS';
